name: lewk-storybook
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
  steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: install-and-build
      run: |
        npm ci
        npm run build-storybook
    
    - name: deploy
      uses: 
      with:
        branch: gh-pages
        folder: docs
